settings:
  backend:
    configure: true
    tenant_id: "111111111-111111111-111111111-111111111"
    subscription_id: "222222222-222222222-222222222-222222222"
    resource_group_name: "rg-my-backend"
    storage_account_name: "strmybackend"
    container_name: "blob-my-backend"
    key: "terraform-caf-es.tfstate"
  core:
    root_id: "myorg"
    root_name: "My Org Ltd."
    default_location: "westeurope"
  connectivity:
    deploy: true
    subscription_id: "333333333-333333333-333333333-333333333"
    custom: true
  management:
    deploy: true
    subscription_id: "444444444-444444444-444444444-444444444"
    custom: true
  custom_management_groups:
    # Add more groups by repeating the following block. The block name (e.g. group1) is irrelevant. Just make sure the block names are different.
    group1:
      parent_management_group_id: "landing_zones"
      id: "newgroup1"
      display_name: "My new Mgmt. Group 1"
      subscription_ids: ["5555555555-5555555555-5555555555-5555555555", "666666666-666666666-666666666-666666666"]
    group2:
      parent_management_group_id: "landing_zones"
      id: "newgroup2"
      display_name: "My new Mgmt. Group 2"
      subscription_ids: ["777777777-777777777-777777777-777777777"]

########################################################
# Documentation
########################################################

##################
# backend (Optional)
##################
# configure: (Optional) Decision (bool: true/false) to add backend configuration.
# tenant_id: (Required) The AAD tenant ID (string) to which the subscription is connected containing the backend storage account.
# subscription_id: (Required) The subscription ID (string) in which the backend storage account is deployed.
# resource_group_name: (Required) The resource group (string) in which the backend storage account is located.
# storage_account_name: (Required) The storage account name (string) in which the blob container is located for storing the Terraform state file.
# container_name: (Required) The blob container name in which the Terraform state file will be stored.
# key: (Required) The name (string) of the Terraform state file.

##################
# core (Required)
##################
# root_id: (Required) The name (string) of the top management group, which will be created, under which all subsequent Managemet Groups will be created, e.g. "mycompany"
# root_name: (Required) The Display name (string) of the top Management Group, e.g. "My Company Ltd."
# default_location: (Required) The default Azure region used for all resources, e.g. "westeurope"

##################
# connectivity (Optional)
##################
# deploy: (Required) Changes the default value (bool: true/false) of variable 'deploy_connectivity_resources' variable.
# subscription_id: (Required) The connectivitiy subscription ID (string).
# custom: (Optional) The option (bool: true/false) to make the variable 'configure_connectivity_resources' available in the variables file.

##################
# management (Optional)
##################
# deploy: Changes the default value (bool: true/false) of variable 'deploy_management_resources' variable.
# subscription_id: The management subscription ID (string).
# custom: (Optional) The option (bool: true/false) to make the variable 'configure_management_resources' available in the variables file.

##################
# custom management groups (Optional)
################## 
# parent_management_group_id: (Required) The ID (string) of the parent management group. The IDs can be extracted here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib/archetype_definitions. It is the last string component of the filename, e.g. connectivity, corp, decommissioned, identity, landing_zones, management, online, platform etc.
# id: (Required) The name (string) of the management group used as an identifier, e.g. own-management-group-1
# display_name: (Required) The display name (string) of the custom management group
# subscription_ids: (Optional) A list of subscription IDs (list of strings) connected to this management group, e.g. ["xxx-xxx-xxx-xxx", "xxx-xxx-xxx-xxx"]. Leave blank, if no subscriptions should be connected to this management group.