settings:
  backend:
    # Add backend configuration? (true/false).
    configure: true
    # The AAD tenant ID to which the subscription is connected containing the backend storage account.
    tenant_id: "tenant_idasdfasdf"
    # The subscription ID in which the backend storage account is deployed.
    subscription_id: "subsc_idasdfasdf"
    # The resource group in which the backend storage account is located.
    resource_group_name: "rg-asdfasdf"
    # The storage account name in which the BLOB container is located for storing the Terraform state file.
    storage_account_name: "strasdfasdf"
    # The blob container name in which the Terraform state file will be stored.
    container_name: "containerasdfasdf"
    # The name of the Terraform state file.
    key: "terraform-caf-es.tfstate"
  core:
    # The name of the top management group, which will be created, under which all subsequent Managemet Groups will be created, e.g. "mycompany"
    root_id: "contoso"
    # The Display name of the top Management Group, e.g. "My Company Ltd."
    root_name: "Contoso Ltd."
    # The default Azure region used for all resources, e.g. "westeurope"
    default_location: "westeurope"
  connectivity:
    # Default value for deploy_connectivity_resources variable will be either true or false.
    deploy: true
    # The connectivitiy subscription ID.
    subscription_id: "connectsubscr"
  management:
    # Default value for deploy_management_resources variable will be either true or false.
    deploy: true
    # The management subscription ID.
    subscription_id: "managesubsc"
  custom_management_groups:
    group1:
      # The ID (name) of the parent management group. The IDs (names) can be found here: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/tree/main/modules/archetypes/lib/archetype_definitions. It is the last string component of the filename, e.g. es_connectivity.
      parent_management_group_id: ""
      # The name of the management group used as an identifier, e.g. own-management-group-1
      id: "own-management-group-1"
      # The display name of the custom management group
      display_name: "zone1 display name"
      # A list of subscription IDs connected to this management group, e.g. ["xxx-xxx-xxx-xxx", "xxx-xxx-xxx-xxx"]
      subscription_ids: [""]