on:
  workflow_call:
    inputs:
      tenant_id:
        description: "The Azure tenant ID."
        required: true
        type: string
      subscription_id:
        description: "The Azure subscription ID."
        required: true
        type: string
      backend_resource_group_name:
        description: "The Azure resource group in which the backend storage account is located."
        required: true
        type: string
      backend_storage_account_name:
        description: "The name of the Azure backend storage account."
        required: true
        type: string
      backend_container_name:
        description: "The name of the Azure backend blob container name."
        required: true
        type: string
      backend_statefile_name:
        description: "The name of the Terraform state file stored in the backend storage."
        required: true
        type: string
      