name: terraform-plan

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:

      ##########################
      # Preparing
      ##########################
      # https://github.tools.sap/ghcom-actions/actions-checkout
      - name: Preparing - Github - checkout respository     
        uses: actions/checkout@v3

      # https://github.com/hashicorp/setup-terraform
      - name: Preparing - Terraform - install CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      ##########################
      # Static Code Analysis
      ##########################
 
      - name: Static Code Analysis - Terraform - format
        run: terraform fmt
 
      - name: Static Code Analysis - Terraform - init
        run: terraform init -input=false
 
      - name: Static Code Analysis - Terraform - validate
        run: terraform validate -no-color
      
      ##########################
      # Plan
      ##########################

      - name: Execution - Terraform - plan
        run: terraform plan